# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 541)
        MainWindow.setMinimumSize(QtCore.QSize(780, 0))
        MainWindow.setStyleSheet("QWidget {\n"
"    color: rgb(26, 34, 47);\n"
"    font: 10pt \"Arial\";\n"
"}\n"
"\n"
"#labelPageName {\n"
"    font-weight: bold;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"\n"
"#frameBarLeft { background-color: rgb(0, 104, 255); }\n"
"#frameBarTop { background-color: rgb(255, 255, 255); }\n"
"#frameMain { background-color: rgb(248, 249, 251); }\n"
"\n"
"#labelIcon {\n"
"    border-image: url(:/icons/logo_white.png);\n"
"}\n"
"\n"
"#pushButtonTop_1, #pushButtonTop_2, #pushButtonTop_3 {\n"
"    padding: 0 0px;\n"
"}\n"
"#frameMain { \n"
"    background-color: rgb(237, 238, 240);\n"
"}\n"
"#framePage1_first { \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"}\n"
"#framePage1_second {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"#scrollArea {\n"
"    border: None;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameBarLeft = QtWidgets.QFrame(self.centralwidget)
        self.frameBarLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBarLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBarLeft.setObjectName("frameBarLeft")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameBarLeft)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelIcon = QtWidgets.QLabel(self.frameBarLeft)
        self.labelIcon.setMinimumSize(QtCore.QSize(32, 32))
        self.labelIcon.setText("")
        self.labelIcon.setObjectName("labelIcon")
        self.verticalLayout_2.addWidget(self.labelIcon)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.frameBarLeft)
        self.pushButton_2.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frameBarLeft)
        self.pushButton_3.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_3.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frameBarLeft)
        self.pushButton_4.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_4.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frameBarLeft)
        self.pushButton_5.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_5.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.horizontalLayout.addWidget(self.frameBarLeft)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameBarTop = QtWidgets.QFrame(self.centralwidget)
        self.frameBarTop.setMinimumSize(QtCore.QSize(0, 55))
        self.frameBarTop.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frameBarTop.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBarTop.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameBarTop.setObjectName("frameBarTop")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameBarTop)
        self.horizontalLayout_2.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelPageName = QtWidgets.QLabel(self.frameBarTop)
        self.labelPageName.setObjectName("labelPageName")
        self.horizontalLayout_2.addWidget(self.labelPageName)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton = QtWidgets.QPushButton(self.frameBarTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.label_2 = QtWidgets.QLabel(self.frameBarTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(32, 32))
        self.label_2.setMaximumSize(QtCore.QSize(32, 32))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frameBarTop)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.page_1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 720, 484))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.framePage1_first = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.framePage1_first.setObjectName("framePage1_first")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.framePage1_first)
        self.horizontalLayout_4.setContentsMargins(20, 20, 20, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.framePage1_first)
        self.pushButton_6.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_6.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_5.addWidget(self.framePage1_first)
        self.framePage1_second = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePage1_second.sizePolicy().hasHeightForWidth())
        self.framePage1_second.setSizePolicy(sizePolicy)
        self.framePage1_second.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.framePage1_second.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePage1_second.setObjectName("framePage1_second")
        self.verticalLayout_5.addWidget(self.framePage1_second)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page_1)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelPageName.setText(_translate("MainWindow", "Организации"))
        self.pushButton.setText(_translate("MainWindow", "Notif"))
        self.label_2.setText(_translate("MainWindow", "Icon"))
