# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 600)
        MainWindow.setStyleSheet("QWidget {\n"
"    color: rgb(26, 34, 47);\n"
"    font: 10pt \"Arial\";\n"
"}\n"
"\n"
"#labelPageName {\n"
"    font-weight: bold;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"\n"
"#frameBarLeft { background-color: rgb(0, 104, 255); }\n"
"#frameBarTop { background-color: rgb(255, 255, 255); }\n"
"#frameMain { background-color: rgb(248, 249, 251); }\n"
"\n"
"#labelIcon {\n"
"    border-image: url(:/icons/logo_white.png);\n"
"}\n"
"\n"
"#pushButtonTop_1, #pushButtonTop_2, #pushButtonTop_3 {\n"
"    padding: 0 0px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameBarLeft = QtWidgets.QFrame(self.centralwidget)
        self.frameBarLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBarLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBarLeft.setObjectName("frameBarLeft")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameBarLeft)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelIcon = QtWidgets.QLabel(self.frameBarLeft)
        self.labelIcon.setMinimumSize(QtCore.QSize(32, 32))
        self.labelIcon.setText("")
        self.labelIcon.setObjectName("labelIcon")
        self.verticalLayout_2.addWidget(self.labelIcon)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.frameBarLeft)
        self.pushButton_2.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frameBarLeft)
        self.pushButton_3.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_3.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frameBarLeft)
        self.pushButton_4.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_4.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frameBarLeft)
        self.pushButton_5.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_5.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.horizontalLayout.addWidget(self.frameBarLeft)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameBarTop = QtWidgets.QFrame(self.centralwidget)
        self.frameBarTop.setMinimumSize(QtCore.QSize(0, 55))
        self.frameBarTop.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frameBarTop.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBarTop.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameBarTop.setObjectName("frameBarTop")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameBarTop)
        self.horizontalLayout_2.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelPageName = QtWidgets.QLabel(self.frameBarTop)
        self.labelPageName.setObjectName("labelPageName")
        self.horizontalLayout_2.addWidget(self.labelPageName)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton = QtWidgets.QPushButton(self.frameBarTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.label_2 = QtWidgets.QLabel(self.frameBarTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(32, 32))
        self.label_2.setMaximumSize(QtCore.QSize(32, 32))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frameBarTop)
        self.frameMain = QtWidgets.QFrame(self.centralwidget)
        self.frameMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMain.setObjectName("frameMain")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameMain)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frameMain)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.stackedWidget_2.addWidget(self.page_6)
        self.verticalLayout_3.addWidget(self.stackedWidget_2)
        self.verticalLayout.addWidget(self.frameMain)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelPageName.setText(_translate("MainWindow", "Организации"))
        self.label_2.setText(_translate("MainWindow", "Иконка"))
